# -*- coding: utf-8 -*-
"""Setting up and Showing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VsmdH2phMAjQkHzNCzObaDvHe1Cf9q-f
"""

# Our first step is to install the opencv-python library.

pip install opencv-python

# We will now import the OpenCV library.

import cv2

# Import the Colab-compatible imshow function

from google.colab.patches import cv2_imshow

# Let's upload the image now.

image = cv2.imread("/content/The-satellite-image-after-the-landslide-event.png")

# Just checking the image upload.

if image is not None:
  # The image will appear in a new window.
  cv2_imshow(image)
else:
  print ("The image couldn't be located.")